version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    
    env_file:
      - ./backend/.env
    
    

  frontend:
    build: ./Frontend/my-app

    ports:
      - "5173:5173"
    
    env_file:
      - ./Frontend/my-app/.env
    
    depends_on:
      - backend

  
  